CATEGORIES = [
    "Code & Development",
    "Project Management & Agile",
    "Documentation",
    "Communication & Reporting",
    "Quality Assurance & Testing",
    "Deployment & Operations",
    "Security & Compliance",
    "Business & Analytics",
    "Stock Market & Investment",
    "Small Business Operations",
]

ROLES = [
    "Engineer",
    "Product Manager",
    "Manager",
    "DevOps",
    "QA",
    "Security",
    "Investor",
    "Small Business Owner",
]

TRIGGERS = ["Scheduled", "GitHub Events", "API/On Demand"]

ROUTINES = [
    # ── Code & Development (1-15) ────────────────────────────────
    {"id": 1, "title": "Code Review Automation", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "Immediate",
     "as_a": "QA Lead", "i_want": "Claude to review every PR for security issues",
     "so_that": "vulnerabilities are caught before merge"},
    {"id": 2, "title": "Test Coverage Monitoring", "role": "Engineer",
     "category": "Code & Development", "trigger": "Scheduled", "frequency": "On commit",
     "as_a": "Developer", "i_want": "Claude to alert me when test coverage drops below 80%",
     "so_that": "code quality doesn't degrade"},
    {"id": 3, "title": "Performance Regression Detection", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "On every new PR",
     "as_a": "Engineering Manager", "i_want": "Claude to run performance benchmarks on every PR",
     "so_that": "we catch slowdowns early"},
    {"id": 4, "title": "Dependency Security Scanning", "role": "Security",
     "category": "Code & Development", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Security Engineer", "i_want": "Claude to scan new dependencies for known vulnerabilities",
     "so_that": "we don't introduce unsafe packages"},
    {"id": 5, "title": "API Endpoint Documentation", "role": "Engineer",
     "category": "Code & Development", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Backend Developer", "i_want": "Claude to auto-generate API documentation from code comments",
     "so_that": "docs stay synchronized with code"},
    {"id": 6, "title": "Breaking Change Detection", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Platform Lead", "i_want": "Claude to flag any breaking changes in a PR",
     "so_that": "API consumers get warnings"},
    {"id": 7, "title": "Code Style Enforcement", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "Immediate",
     "as_a": "Tech Lead", "i_want": "Claude to check every PR for style violations",
     "so_that": "code stays consistent without manual review"},
    {"id": 8, "title": "Merge Conflict Resolution", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "On conflict",
     "as_a": "Developer", "i_want": "Claude to identify and suggest fixes for merge conflicts",
     "so_that": "I spend less time untangling them"},
    {"id": 9, "title": "Dead Code Detection", "role": "Engineer",
     "category": "Code & Development", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Refactoring Champion", "i_want": "Claude to identify unused functions and classes monthly",
     "so_that": "we keep the codebase clean"},
    {"id": 10, "title": "SQL Query Optimization", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Database Administrator", "i_want": "Claude to review new SQL queries for performance issues",
     "so_that": "slow queries don't reach production"},
    {"id": 11, "title": "Multi-SDK Sync", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "On merge",
     "as_a": "Platform Team Lead", "i_want": "Claude to port changes from our Python SDK to our Go SDK",
     "so_that": "libraries stay synchronized"},
    {"id": 12, "title": "Changelog Generation", "role": "Product Manager",
     "category": "Code & Development", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Product Manager", "i_want": "Claude to generate a changelog from merged PRs weekly",
     "so_that": "we have release notes ready"},
    {"id": 13, "title": "Architecture Violation Detection", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Architect", "i_want": "Claude to flag violations of our ADRs in code reviews",
     "so_that": "architecture decisions are enforced"},
    {"id": 14, "title": "Complexity Analysis", "role": "Engineer",
     "category": "Code & Development", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Tech Lead", "i_want": "Claude to calculate cyclomatic complexity for new code",
     "so_that": "I can identify overly complex functions"},
    {"id": 15, "title": "Licensing Compliance Check", "role": "Security",
     "category": "Code & Development", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Legal/Compliance Officer", "i_want": "Claude to verify all dependencies have approved licenses",
     "so_that": "we avoid legal issues"},

    # ── Project Management & Agile (16-35) ───────────────────────
    {"id": 16, "title": "Daily Standup Digest", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Scrum Master", "i_want": "Claude to generate a standup summary from git commits",
     "so_that": "our team has a daily brief"},
    {"id": 17, "title": "Sprint Planning Assistance", "role": "Product Manager",
     "category": "Project Management & Agile", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Product Owner", "i_want": "Claude to suggest sprint stories based on our backlog and team velocity",
     "so_that": "planning meetings are shorter"},
    {"id": 18, "title": "Issue Triage Automation", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Engineering Manager", "i_want": "Claude to categorize and label new GitHub issues nightly",
     "so_that": "backlog is organized each morning"},
    {"id": 19, "title": "Blocker Identification", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Twice daily",
     "as_a": "Scrum Master", "i_want": "Claude to identify blockers from PR comments and Jira",
     "so_that": "risks surface early"},
    {"id": 20, "title": "Sprint Burndown Analysis", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Agile Coach", "i_want": "Claude to analyze sprint progress and predict completion",
     "so_that": "we can course-correct mid-sprint"},
    {"id": 21, "title": "Retrospective Report Generation", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Scrum Master", "i_want": "Claude to compile sprint data for retrospectives",
     "so_that": "I have talking points ready"},
    {"id": 22, "title": "Story Point Estimation", "role": "Engineer",
     "category": "Project Management & Agile", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Tech Lead", "i_want": "Claude to suggest story point estimates based on historical velocity",
     "so_that": "estimation is faster"},
    {"id": 23, "title": "Capacity Planning", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Engineering Manager", "i_want": "Claude to forecast team capacity for the next 3 sprints",
     "so_that": "we can commit with confidence"},
    {"id": 24, "title": "Dependency Mapping", "role": "Product Manager",
     "category": "Project Management & Agile", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Product Owner", "i_want": "Claude to identify dependencies between stories in a sprint",
     "so_that": "we sequence work correctly"},
    {"id": 25, "title": "On-Demand Team Report", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Engineering Manager", "i_want": "Claude to generate team health reports on demand",
     "so_that": "I can answer leadership questions quickly"},
    {"id": 26, "title": "Release Planning", "role": "Product Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "On release",
     "as_a": "Product Manager", "i_want": "Claude to group completed stories into release notes",
     "so_that": "customers know what's new"},
    {"id": 27, "title": "Velocity Trending", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Scrum Master", "i_want": "Claude to track velocity trends over 10 sprints",
     "so_that": "we can identify team improvement"},
    {"id": 28, "title": "Priority Conflict Resolution", "role": "Product Manager",
     "category": "Project Management & Agile", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Product Owner", "i_want": "Claude to identify conflicting priorities in the backlog",
     "so_that": "we align on sequencing"},
    {"id": 29, "title": "Epic Breakdown", "role": "Product Manager",
     "category": "Project Management & Agile", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Product Manager", "i_want": "Claude to break down epics into user stories",
     "so_that": "they're ready for sprint planning"},
    {"id": 30, "title": "Stakeholder Status Update", "role": "Product Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Product Manager", "i_want": "Claude to generate weekly stakeholder updates",
     "so_that": "leadership is informed without my effort"},
    {"id": 31, "title": "Sprint Goal Tracking", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Scrum Master", "i_want": "Claude to remind the team of sprint goals daily",
     "so_that": "focus is maintained"},
    {"id": 32, "title": "Action Item Follow-up", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Scrum Master", "i_want": "Claude to remind owners of action items from standups",
     "so_that": "nothing falls through cracks"},
    {"id": 33, "title": "Team Workload Balancing", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Engineering Manager", "i_want": "Claude to suggest story assignments based on workload",
     "so_that": "team load is even"},
    {"id": 34, "title": "Milestone Tracking", "role": "Product Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Product Manager", "i_want": "Claude to track progress toward major milestones",
     "so_that": "we stay on schedule"},
    {"id": 35, "title": "Unplanned Work Identification", "role": "Manager",
     "category": "Project Management & Agile", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Scrum Master", "i_want": "Claude to flag unplanned work added to the sprint",
     "so_that": "scope creep is visible"},

    # ── Documentation (36-48) ────────────────────────────────────
    {"id": 36, "title": "Documentation Drift Detection", "role": "Engineer",
     "category": "Documentation", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Tech Lead", "i_want": "Claude to scan for API documentation that doesn't match code",
     "so_that": "docs stay accurate"},
    {"id": 37, "title": "README Update Suggestions", "role": "Engineer",
     "category": "Documentation", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Developer", "i_want": "Claude to suggest README updates based on recent code changes",
     "so_that": "setup instructions stay current"},
    {"id": 38, "title": "ADR Suggestions", "role": "Engineer",
     "category": "Documentation", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Architect", "i_want": "Claude to identify missing ADRs for significant architectural changes",
     "so_that": "decisions are documented"},
    {"id": 39, "title": "API Client Library Documentation", "role": "Engineer",
     "category": "Documentation", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "DevRel Engineer", "i_want": "Claude to auto-generate API client docs from OpenAPI specs",
     "so_that": "SDKs are always documented"},
    {"id": 40, "title": "Troubleshooting Guide Generation", "role": "Manager",
     "category": "Documentation", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Support Manager", "i_want": "Claude to generate troubleshooting guides from common support tickets",
     "so_that": "documentation helps customers"},
    {"id": 41, "title": "Code Comment Quality Check", "role": "Engineer",
     "category": "Documentation", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Code Reviewer", "i_want": "Claude to flag functions with missing comments",
     "so_that": "code is self-documenting"},
    {"id": 42, "title": "Runbook Creation", "role": "DevOps",
     "category": "Documentation", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "On-Call Engineer", "i_want": "Claude to create runbooks for common operational procedures",
     "so_that": "incident response is faster"},
    {"id": 43, "title": "Migration Guide Generation", "role": "Product Manager",
     "category": "Documentation", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Product Manager", "i_want": "Claude to create migration guides when APIs change",
     "so_that": "customers can upgrade smoothly"},
    {"id": 44, "title": "FAQ From Slack", "role": "Manager",
     "category": "Documentation", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Support Lead", "i_want": "Claude to build an FAQ from repeated Slack questions",
     "so_that": "self-service improves"},
    {"id": 45, "title": "Feature Documentation", "role": "Product Manager",
     "category": "Documentation", "trigger": "Scheduled", "frequency": "On release",
     "as_a": "Product Manager", "i_want": "Claude to document new features automatically",
     "so_that": "docs are complete at launch"},
    {"id": 46, "title": "Deprecation Notices", "role": "Engineer",
     "category": "Documentation", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Platform Lead", "i_want": "Claude to generate deprecation notices for old APIs",
     "so_that": "users plan migrations"},
    {"id": 47, "title": "Configuration Guide", "role": "DevOps",
     "category": "Documentation", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "DevOps Engineer", "i_want": "Claude to generate configuration guides from infrastructure code",
     "so_that": "admins know how to operate systems"},
    {"id": 48, "title": "Onboarding Checklist Generation", "role": "Manager",
     "category": "Documentation", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Engineering Manager", "i_want": "Claude to auto-generate onboarding checklists for new team members",
     "so_that": "they get up to speed faster"},

    # ── Communication & Reporting (49-65) ────────────────────────
    {"id": 49, "title": "Weekly Team Newsletter", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Team Lead", "i_want": "Claude to compile wins and metrics into a weekly newsletter",
     "so_that": "the team celebrates progress"},
    {"id": 50, "title": "Executive Summary", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Engineering Director", "i_want": "Claude to create executive summaries of technical progress",
     "so_that": "leadership understands impact"},
    {"id": 51, "title": "Customer Success Update", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Customer Success Manager", "i_want": "Claude to generate customer health summaries",
     "so_that": "I can proactively support accounts"},
    {"id": 52, "title": "Incident Post-Mortem", "role": "DevOps",
     "category": "Communication & Reporting", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Incident Commander", "i_want": "Claude to compile incident data into a post-mortem",
     "so_that": "we learn from outages"},
    {"id": 53, "title": "Code Contributor Recognition", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Manager", "i_want": "Claude to identify top contributors monthly",
     "so_that": "I can recognize and celebrate them"},
    {"id": 54, "title": "Team Metrics Dashboard", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Engineering Manager", "i_want": "Claude to generate team metrics weekly",
     "so_that": "I have data for 1-on-1s"},
    {"id": 55, "title": "Customer Feature Request Summary", "role": "Product Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Product Manager", "i_want": "Claude to summarize feature requests by category monthly",
     "so_that": "we see demand patterns"},
    {"id": 56, "title": "Community Engagement Report", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Developer Relations Manager", "i_want": "Claude to track community contributions weekly",
     "so_that": "I see who's engaged"},
    {"id": 57, "title": "Conference Talk Suggestions", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Developer Relations Manager", "i_want": "Claude to identify interesting technical topics from PRs",
     "so_that": "we find talks worth proposing"},
    {"id": 58, "title": "Partner Integration Status", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Partnerships Manager", "i_want": "Claude to summarize partner integration progress weekly",
     "so_that": "stakeholders are informed"},
    {"id": 59, "title": "Product Launch Announcement", "role": "Product Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "On release",
     "as_a": "Product Manager", "i_want": "Claude to draft launch announcements from completed stories",
     "so_that": "marketing has copy ready"},
    {"id": 60, "title": "Engineering Hiring Needs", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Engineering Manager", "i_want": "Claude to identify skills gaps from PR patterns",
     "so_that": "we know what to hire for"},
    {"id": 61, "title": "Technical Debt Summary", "role": "Engineer",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Tech Lead", "i_want": "Claude to summarize technical debt monthly",
     "so_that": "I can advocate for refactoring time"},
    {"id": 62, "title": "Competitive Analysis", "role": "Product Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Product Manager", "i_want": "Claude to track competitor features mentioned in issues",
     "so_that": "we stay competitive"},
    {"id": 63, "title": "Team Bandwidth Alert", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Scrum Master", "i_want": "Claude to alert me when the team is over-capacity",
     "so_that": "we can reduce scope"},
    {"id": 64, "title": "Risk Register Update", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Program Manager", "i_want": "Claude to identify risks from sprint data",
     "so_that": "the risk register stays current"},
    {"id": 65, "title": "Board Meeting Prep", "role": "Manager",
     "category": "Communication & Reporting", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Executive", "i_want": "Claude to prepare board meeting materials on demand",
     "so_that": "I'm ready for investor questions"},

    # ── Quality Assurance & Testing (66-76) ──────────────────────
    {"id": 66, "title": "Flaky Test Detection", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "QA Engineer", "i_want": "Claude to identify flaky tests from CI logs",
     "so_that": "we fix unreliable tests"},
    {"id": 67, "title": "Test Case Generation", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "QA Lead", "i_want": "Claude to suggest test cases for new features",
     "so_that": "coverage is comprehensive"},
    {"id": 68, "title": "Cross-Browser Testing Summary", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "QA Engineer", "i_want": "Claude to summarize cross-browser test results",
     "so_that": "we know which browsers are broken"},
    {"id": 69, "title": "Bug Severity Classification", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "GitHub Events", "frequency": "On issue creation",
     "as_a": "QA Manager", "i_want": "Claude to classify bugs by severity",
     "so_that": "critical issues get priority"},
    {"id": 70, "title": "Regression Test Suite Recommendation", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "QA Lead", "i_want": "Claude to suggest regression tests based on code changes",
     "so_that": "we test the right areas"},
    {"id": 71, "title": "Test Coverage Report", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Tech Lead", "i_want": "Claude to generate test coverage reports",
     "so_that": "we can see gaps"},
    {"id": 72, "title": "Accessibility Compliance Check", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Compliance Officer", "i_want": "Claude to check for accessibility violations",
     "so_that": "our product is accessible"},
    {"id": 73, "title": "Load Testing Report", "role": "DevOps",
     "category": "Quality Assurance & Testing", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Infrastructure Engineer", "i_want": "Claude to run load tests weekly",
     "so_that": "we know if performance degrades"},
    {"id": 74, "title": "Security Vulnerability Report", "role": "Security",
     "category": "Quality Assurance & Testing", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Security Officer", "i_want": "Claude to run security scans weekly",
     "so_that": "we catch vulnerabilities early"},
    {"id": 75, "title": "Usability Issue Detection", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "UX Designer", "i_want": "Claude to flag potential UX issues from code changes",
     "so_that": "we can test them"},
    {"id": 76, "title": "QA Triage Summary", "role": "QA",
     "category": "Quality Assurance & Testing", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "QA Manager", "i_want": "Claude to triage bugs daily",
     "so_that": "they're ready for team assignment"},

    # ── Deployment & Operations (77-86) ──────────────────────────
    {"id": 77, "title": "Deployment Verification", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "API/On Demand", "frequency": "On each deployment",
     "as_a": "DevOps Engineer", "i_want": "Claude to verify production deployments with smoke tests",
     "so_that": "bad deployments are caught immediately"},
    {"id": 78, "title": "Log Analysis & Alerting", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "Scheduled", "frequency": "Continuous",
     "as_a": "On-Call Engineer", "i_want": "Claude to analyze error logs and alert on spikes",
     "so_that": "I catch issues before customers do"},
    {"id": 79, "title": "Database Migration Review", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "DBA", "i_want": "Claude to review database migrations for safety",
     "so_that": "we avoid data loss"},
    {"id": 80, "title": "Infrastructure Cost Optimization", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Finance Manager", "i_want": "Claude to identify over-provisioned resources monthly",
     "so_that": "we optimize cloud spend"},
    {"id": 81, "title": "Backup Verification", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "DBA", "i_want": "Claude to verify backups completed successfully",
     "so_that": "we're protected from data loss"},
    {"id": 82, "title": "DNS & Certificate Expiration", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "DevOps Engineer", "i_want": "Claude to monitor for expiring certificates and DNS issues",
     "so_that": "we avoid service disruptions"},
    {"id": 83, "title": "Configuration Drift Detection", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "DevOps Engineer", "i_want": "Claude to detect configuration drift from infrastructure as code",
     "so_that": "production matches our spec"},
    {"id": 84, "title": "Disaster Recovery Testing", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Disaster Recovery Manager", "i_want": "Claude to run DR tests monthly",
     "so_that": "we know we can recover from disasters"},
    {"id": 85, "title": "Blue-Green Deployment Validation", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "API/On Demand", "frequency": "On each deployment",
     "as_a": "Deployment Lead", "i_want": "Claude to validate blue-green deployments",
     "so_that": "we can roll back quickly if needed"},
    {"id": 86, "title": "Rollback Recommendation", "role": "DevOps",
     "category": "Deployment & Operations", "trigger": "API/On Demand", "frequency": "On anomaly detection",
     "as_a": "On-Call Engineer", "i_want": "Claude to recommend rollbacks when errors spike",
     "so_that": "we recover quickly"},

    # ── Security & Compliance (87-95) ────────────────────────────
    {"id": 87, "title": "Secrets Scanning", "role": "Security",
     "category": "Security & Compliance", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Security Officer", "i_want": "Claude to scan code for exposed secrets",
     "so_that": "credentials aren't leaked"},
    {"id": 88, "title": "Compliance Audit Trail", "role": "Security",
     "category": "Security & Compliance", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Compliance Officer", "i_want": "Claude to generate audit trails for compliance",
     "so_that": "we pass audits"},
    {"id": 89, "title": "GDPR Data Processing Review", "role": "Security",
     "category": "Security & Compliance", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Data Protection Officer", "i_want": "Claude to review code for GDPR compliance",
     "so_that": "we protect customer data"},
    {"id": 90, "title": "Security Incident Response", "role": "Security",
     "category": "Security & Compliance", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Security Officer", "i_want": "Claude to assist with incident response by gathering evidence",
     "so_that": "investigations are thorough"},
    {"id": 91, "title": "Access Control Review", "role": "Security",
     "category": "Security & Compliance", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Security Officer", "i_want": "Claude to review access control logs monthly",
     "so_that": "we catch unauthorized access"},
    {"id": 92, "title": "Vulnerability Disclosure Coordination", "role": "Security",
     "category": "Security & Compliance", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Security Officer", "i_want": "Claude to manage vulnerability disclosures",
     "so_that": "we respond responsibly"},
    {"id": 93, "title": "Third-Party Security Assessment", "role": "Security",
     "category": "Security & Compliance", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Security Officer", "i_want": "Claude to assess third-party vendor security",
     "so_that": "we manage supply chain risk"},
    {"id": 94, "title": "Security Training Reminder", "role": "Security",
     "category": "Security & Compliance", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Security Officer", "i_want": "Claude to send security training reminders quarterly",
     "so_that": "team stays aware"},
    {"id": 95, "title": "Code Security Baseline", "role": "Security",
     "category": "Security & Compliance", "trigger": "GitHub Events", "frequency": "On PR open",
     "as_a": "Security Officer", "i_want": "Claude to enforce security baselines across all services",
     "so_that": "we maintain standards"},

    # ── Business & Analytics (96-100) ────────────────────────────
    {"id": 96, "title": "Product Usage Analytics", "role": "Product Manager",
     "category": "Business & Analytics", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Product Manager", "i_want": "Claude to summarize user behavior weekly",
     "so_that": "we see adoption trends"},
    {"id": 97, "title": "Revenue Impact Analysis", "role": "Product Manager",
     "category": "Business & Analytics", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Finance Manager", "i_want": "Claude to calculate revenue impact of features",
     "so_that": "we prioritize high-ROI work"},
    {"id": 98, "title": "Customer Churn Analysis", "role": "Product Manager",
     "category": "Business & Analytics", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Customer Success Manager", "i_want": "Claude to identify at-risk customers",
     "so_that": "we can intervene early"},
    {"id": 99, "title": "Market Opportunity Assessment", "role": "Product Manager",
     "category": "Business & Analytics", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Product Manager", "i_want": "Claude to identify market opportunities from customer feedback",
     "so_that": "we know what to build"},
    {"id": 100, "title": "Competitive Feature Parity Check", "role": "Product Manager",
     "category": "Business & Analytics", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Product Manager", "i_want": "Claude to compare our features to competitors monthly",
     "so_that": "we know where we lag"},

    # ── Stock Market & Investment (101-120) ──────────────────────
    {"id": 101, "title": "Daily Portfolio Summary", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Investor", "i_want": "Claude to generate a daily portfolio summary with gains/losses",
     "so_that": "I see my investments at a glance"},
    {"id": 102, "title": "Stock Price Alert", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Every 15 minutes",
     "as_a": "Trader", "i_want": "Claude to alert me when stocks hit target prices",
     "so_that": "I don't miss buy/sell opportunities"},
    {"id": 103, "title": "Dividend Tracker", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Income Investor", "i_want": "Claude to track upcoming dividend payments",
     "so_that": "I know when to expect income"},
    {"id": 104, "title": "Tax Loss Harvesting Recommendations", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Tax-Conscious Investor", "i_want": "Claude to identify tax loss harvesting opportunities",
     "so_that": "I minimize taxes"},
    {"id": 105, "title": "Earnings Report Analysis", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "API/On Demand", "frequency": "On report release",
     "as_a": "Stock Picker", "i_want": "Claude to analyze earnings reports and flag surprises",
     "so_that": "I see investment implications"},
    {"id": 106, "title": "Portfolio Rebalancing Alert", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Passive Investor", "i_want": "Claude to alert me when allocations drift > 5%",
     "so_that": "I know when to rebalance"},
    {"id": 107, "title": "Sector Performance Tracking", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Diversified Investor", "i_want": "Claude to track sector performance weekly",
     "so_that": "I see which areas are hot"},
    {"id": 108, "title": "Correlation Analysis", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Risk Manager", "i_want": "Claude to analyze correlation between my holdings",
     "so_that": "I can reduce portfolio risk"},
    {"id": 109, "title": "IPO Screening", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Growth Investor", "i_want": "Claude to screen upcoming IPOs for my criteria",
     "so_that": "I find investment opportunities"},
    {"id": 110, "title": "Debt vs. Equity Analysis", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Fundamental Analyst", "i_want": "Claude to compare company debt levels",
     "so_that": "I assess financial health"},
    {"id": 111, "title": "Interest Rate Impact Analysis", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Fixed Income Investor", "i_want": "Claude to analyze how rate changes affect my bonds",
     "so_that": "I understand risks"},
    {"id": 112, "title": "Dividend History Analysis", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Dividend Investor", "i_want": "Claude to track dividend history of my holdings",
     "so_that": "I spot cuts before they happen"},
    {"id": 113, "title": "Year-to-Date Performance Report", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Self-Directed Investor", "i_want": "Claude to generate YTD performance reports",
     "so_that": "I track progress toward goals"},
    {"id": 114, "title": "Insider Trading Alerts", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Contrarian Investor", "i_want": "Claude to alert me to insider buys/sells",
     "so_that": "I see what insiders think"},
    {"id": 115, "title": "Volatility Spike Detection", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Hourly",
     "as_a": "Risk-Aware Investor", "i_want": "Claude to alert me to unusual volatility",
     "so_that": "I can investigate causes"},
    {"id": 116, "title": "Competitor Comparison", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Sector Investor", "i_want": "Claude to compare competitors' metrics monthly",
     "so_that": "I identify the best positioned"},
    {"id": 117, "title": "Economic Calendar Tracking", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Macro Investor", "i_want": "Claude to alert me to important economic releases",
     "so_that": "I prepare for market moves"},
    {"id": 118, "title": "Valuation Metric Analysis", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Value Investor", "i_want": "Claude to track P/E, P/B, PEG ratios",
     "so_that": "I find undervalued stocks"},
    {"id": 119, "title": "Crypto Portfolio Tracking", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Digital Asset Investor", "i_want": "Claude to track crypto holdings across exchanges",
     "so_that": "I see consolidated portfolio"},
    {"id": 120, "title": "Investment Goal Progress Report", "role": "Investor",
     "category": "Stock Market & Investment", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Goal-Focused Investor", "i_want": "Claude to report progress toward retirement/college/goals",
     "so_that": "I know if I'm on track"},

    # ── Small Business Operations (121-150) ──────────────────────
    {"id": 121, "title": "Daily Sales Summary", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Small Business Owner", "i_want": "Claude to summarize daily sales by product/customer",
     "so_that": "I know how business is doing"},
    {"id": 122, "title": "Customer Order Tracking", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Twice daily",
     "as_a": "Fulfillment Manager", "i_want": "Claude to track order status and flag delays",
     "so_that": "customers aren't left wondering"},
    {"id": 123, "title": "Inventory Low Stock Alerts", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Warehouse Manager", "i_want": "Claude to alert when inventory falls below thresholds",
     "so_that": "I reorder before stockouts"},
    {"id": 124, "title": "Supplier Performance Scorecard", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Procurement Manager", "i_want": "Claude to track supplier metrics (on-time, quality)",
     "so_that": "I hold suppliers accountable"},
    {"id": 125, "title": "Cash Flow Forecast", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Business Owner", "i_want": "Claude to forecast cash flow monthly",
     "so_that": "I manage working capital"},
    {"id": 126, "title": "Expense Categorization", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "API/On Demand", "frequency": "On expense entry",
     "as_a": "Accountant", "i_want": "Claude to automatically categorize expenses",
     "so_that": "accounting is faster and more accurate"},
    {"id": 127, "title": "Overdue Invoice Collection", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Finance Manager", "i_want": "Claude to track overdue invoices and alert on collection",
     "so_that": "I improve cash collection"},
    {"id": 128, "title": "Profitability by Product", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Product Manager", "i_want": "Claude to calculate profitability by product/SKU",
     "so_that": "I know what to promote"},
    {"id": 129, "title": "Customer Lifetime Value Analysis", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Marketing Manager", "i_want": "Claude to calculate CLV by customer segment",
     "so_that": "I focus on high-value customers"},
    {"id": 130, "title": "Payroll Compliance Check", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "HR Manager", "i_want": "Claude to review payroll for compliance (tax withholding, breaks)",
     "so_that": "we stay compliant"},
    {"id": 131, "title": "Employee Performance Review Prep", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "API/On Demand", "frequency": "Quarterly",
     "as_a": "Manager", "i_want": "Claude to compile performance data for reviews",
     "so_that": "reviews are data-driven"},
    {"id": 132, "title": "Customer Support Ticket Triage", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "3 times daily",
     "as_a": "Support Manager", "i_want": "Claude to categorize and prioritize support tickets",
     "so_that": "urgent issues get attention"},
    {"id": 133, "title": "Website Traffic Analysis", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Marketing Manager", "i_want": "Claude to analyze website traffic weekly",
     "so_that": "I see what content resonates"},
    {"id": 134, "title": "Social Media Engagement Report", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Social Media Manager", "i_want": "Claude to summarize engagement metrics daily",
     "so_that": "I see what content performs"},
    {"id": 135, "title": "Email Campaign Performance", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "API/On Demand", "frequency": "On demand",
     "as_a": "Marketing Manager", "i_want": "Claude to analyze email campaign results",
     "so_that": "I improve open/click rates"},
    {"id": 136, "title": "Customer Feedback Compilation", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Product Manager", "i_want": "Claude to compile customer feedback into themes",
     "so_that": "I see improvement opportunities"},
    {"id": 137, "title": "Competitive Price Monitoring", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Pricing Manager", "i_want": "Claude to monitor competitor prices daily",
     "so_that": "I stay competitive"},
    {"id": 138, "title": "Warranty & Returns Analysis", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Quality Manager", "i_want": "Claude to track warranty claims and returns",
     "so_that": "I spot quality issues"},
    {"id": 139, "title": "License & Permit Compliance", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Operations Manager", "i_want": "Claude to track business license and permit expirations",
     "so_that": "we don't lose credentials"},
    {"id": 140, "title": "Insurance Policy Review", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Risk Manager", "i_want": "Claude to review insurance coverage monthly",
     "so_that": "we maintain proper protection"},
    {"id": 141, "title": "Contract Renewal Alerts", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Contracts Manager", "i_want": "Claude to alert on contract renewals",
     "so_that": "we don't miss deadlines or price increases"},
    {"id": 142, "title": "Vendor Invoice Reconciliation", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Daily",
     "as_a": "Accounts Payable Manager", "i_want": "Claude to match invoices to POs and receipts",
     "so_that": "payments are accurate"},
    {"id": 143, "title": "Budget vs. Actual Variance", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Finance Manager", "i_want": "Claude to analyze budget variances monthly",
     "so_that": "I manage to budget"},
    {"id": 144, "title": "Quarterly Tax Estimate", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Business Owner", "i_want": "Claude to calculate quarterly tax estimates",
     "so_that": "I set aside proper tax amounts"},
    {"id": 145, "title": "Growth Metrics Dashboard", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Business Owner", "i_want": "Claude to compile growth metrics (MoM, YoY)",
     "so_that": "I see business trajectory"},
    {"id": 146, "title": "Employee Handbook Updates", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "HR Manager", "i_want": "Claude to flag policy updates needed based on new regulations",
     "so_that": "handbook stays compliant"},
    {"id": 147, "title": "Seasonal Planning Recommendations", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Quarterly",
     "as_a": "Retail Manager", "i_want": "Claude to suggest seasonal staffing and inventory based on history",
     "so_that": "I prepare proactively"},
    {"id": 148, "title": "Customer Win/Loss Analysis", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Sales Manager", "i_want": "Claude to analyze why customers were won or lost",
     "so_that": "I improve sales strategy"},
    {"id": 149, "title": "Business Insurance Claims Tracking", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Weekly",
     "as_a": "Risk Manager", "i_want": "Claude to track filed insurance claims",
     "so_that": "we follow up to resolution"},
    {"id": 150, "title": "Annual Business Plan Progress", "role": "Small Business Owner",
     "category": "Small Business Operations", "trigger": "Scheduled", "frequency": "Monthly",
     "as_a": "Business Owner", "i_want": "Claude to track progress toward annual goals monthly",
     "so_that": "I course-correct as needed"},
]
